### ISSUE TITLE
Building binaries for osx-arm64

### ISSUE THREAD

**Issue by EdanToledo** [cyberbotics/webots-controller#2]
Hello, I was wondering if you could build the binaries for osx-arm64 of this library. There are issues with interfacing ros2 and webots on m1 macs and it's hard to set up. If these binaries could be built, it would greatly help downstream for other things as well. Thanks so much. I hope this is possible.

**Comment by omichel** [comment]
We do not support ROS 2 on macOS, this is why there is neither osx-arm64 nor osx-x86_64 binaries on this repository.
However, we are currently working a solution for macOS users:
1. They should install ROS2 in a Linux docker on their macOS system, including the webots_ros2 packages.
2. They should install Webots for macOS (which has full support for arm64).
3. The webots_ros2 packages running in Linux/Docker will communicate with Webots running natively on macOS (arm64/x86_64).

If you are interested to beta-test this solution, please write to support@cyberbotics.com so that we keep you in the loop.

**Comment by omichel** [comment]
Note: the arm64/x86_64 fat binaries for the libController are available in the macOS packages of Webots since version R2022b.
